const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.jumpthru,
		C3.Behaviors.Sin,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Camera3D,
		C3.Plugins.Touch,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Touch.Cnds.OnTouchObject
	];
};
self.C3_JsPropNameTable = [
	{Mosaico: 0},
	{Sólido: 0},
	{chao: 0},
	{janela: 0},
	{morteEspinho: 0},
	{PularAtravés: 0},
	{Senóide: 0},
	{plataforma: 0},
	{plataforma2: 0},
	{morte: 0},
	{portal: 0},
	{portaFechada: 0},
	{coin: 0},
	{coin2: 0},
	{Áudio: 0},
	{Teclado: 0},
	{Mosaico2: 0},
	{personagem2: 0},
	{comecar: 0},
	{gameover: 0},
	{Mosaico3: 0},
	{Plataforma: 0},
	{bloco: 0},
	{inimigo: 0},
	{plataforma3: 0},
	{coin3: 0},
	{lava: 0},
	{CentrarEm: 0},
	{heroiverdadde: 0},
	{contavida: 0},
	{bau: 0},
	{inimigo2: 0},
	{inimigoo: 0},
	{inimigo3: 0},
	{inimigoBolinha: 0},
	{obstaculo2: 0},
	{obstaculo3: 0},
	{bolinhainimiga: 0},
	{fundo: 0},
	{carreagndo: 0},
	{carregandoo: 0},
	{espinho: 0},
	{plataformagirante: 0},
	{baudinheiro: 0},
	{caixa: 0},
	{chaveGirando: 0},
	{plataformagirando: 0},
	{inimigo4: 0},
	{inimigo5: 0},
	{sensor: 0},
	{sensor2: 0},
	{balao: 0},
	{Mosaico4: 0},
	{FUNDOCARTA: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{esquerdo: 0},
	{esquerdo2: 0},
	{esquerdo3: 0},
	{Toque: 0}
];

self.InstanceType = {
	Mosaico: class extends self.ITilemapInstance {},
	chao: class extends self.ISpriteInstance {},
	janela: class extends self.ISpriteInstance {},
	morteEspinho: class extends self.ISpriteInstance {},
	plataforma: class extends self.ISpriteInstance {},
	plataforma2: class extends self.ISpriteInstance {},
	morte: class extends self.ISpriteInstance {},
	portal: class extends self.ISpriteInstance {},
	portaFechada: class extends self.ISpriteInstance {},
	coin: class extends self.ISpriteInstance {},
	coin2: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	Teclado: class extends self.IInstance {},
	Mosaico2: class extends self.ITilemapInstance {},
	personagem2: class extends self.ISpriteInstance {},
	comecar: class extends self.ISpriteInstance {},
	gameover: class extends self.ISpriteInstance {},
	Mosaico3: class extends self.ITilemapInstance {},
	bloco: class extends self.ISpriteInstance {},
	inimigo: class extends self.ISpriteInstance {},
	plataforma3: class extends self.ISpriteInstance {},
	coin3: class extends self.ISpriteInstance {},
	lava: class extends self.ISpriteInstance {},
	heroiverdadde: class extends self.ISpriteInstance {},
	contavida: class extends self.ISpriteInstance {},
	bau: class extends self.ISpriteInstance {},
	inimigo2: class extends self.ISpriteInstance {},
	inimigoo: class extends self.ISpriteInstance {},
	inimigo3: class extends self.ISpriteInstance {},
	inimigoBolinha: class extends self.ISpriteInstance {},
	obstaculo2: class extends self.IInstance {},
	obstaculo3: class extends self.ISpriteInstance {},
	bolinhainimiga: class extends self.ISpriteInstance {},
	fundo: class extends self.ISpriteInstance {},
	carreagndo: class extends self.ISpriteInstance {},
	carregandoo: class extends self.ISpriteInstance {},
	espinho: class extends self.ISpriteInstance {},
	plataformagirante: class extends self.ISpriteInstance {},
	baudinheiro: class extends self.ISpriteInstance {},
	caixa: class extends self.ISpriteInstance {},
	chaveGirando: class extends self.ISpriteInstance {},
	plataformagirando: class extends self.ISpriteInstance {},
	inimigo4: class extends self.ISpriteInstance {},
	inimigo5: class extends self.ISpriteInstance {},
	sensor: class extends self.ISpriteInstance {},
	sensor2: class extends self.ISpriteInstance {},
	balao: class extends self.ISpriteInstance {},
	Mosaico4: class extends self.ITilemapInstance {},
	FUNDOCARTA: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	esquerdo: class extends self.ISpriteInstance {},
	esquerdo2: class extends self.ISpriteInstance {},
	esquerdo3: class extends self.ISpriteInstance {},
	Toque: class extends self.IInstance {}
}